name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Check if this is a version commit
        id: check_commit
        run: |
          if [[ $(git log -1 --pretty=%B) == *"Update version"* ]]; then
            echo "Skipping version update commit"
            exit 0
          fi

      - name: Increment Version
        run: |
          mvn versions:set -DnewVersion=1.0.$(( $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | grep -o '[0-9]*$') + 1 ))
          mvn clean install

      - name: Commit and push version change
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add pom.xml
          git commit -m "Update version"
          git push

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t omerapp99/simple-java-maven-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push omerapp99/simple-java-maven-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Docker Image
        run: |
          docker-compose up -d
