name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven 3.9.2
        run: |
          curl -sL https://dlcdn.apache.org/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz -o maven.tar.gz
          tar -xzf maven.tar.gz
          sudo mv apache-maven-3.9.2 /opt/maven
          sudo ln -s /opt/maven/bin/mvn /usr/bin/mvn

      - name: Confirm Maven Version
        run: |
          mvn -version

      - name: Increment Version
        run: |
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          new_version=$(echo $current_version | sed 's/[0-9]*$/&+1/' | bc)
          mvn versions:set -DnewVersion=1.0.$new_version
          mvn versions:commit
          mvn clean install

      - name: Commit and push version change
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add pom.xml
          git commit -m "Update version to 1.0.$new_version"
          git push

  build:
    runs-on: ubuntu-latest
    needs: versioning  # Ensures this job runs after 'versioning'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build --no-cache -t omerapp99/simple-java-maven-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push omerapp99/simple-java-maven-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures this job runs after 'build'

    steps:
      - name: Install Docker and Docker Compose
        run: |
          curl -fsSL https://get.docker.com | sudo bash
          sudo usermod -aG docker $USER
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Deploy Docker Image
        run: |
          docker-compose up -d