name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Increment Version
        run: |
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          
          IFS='.' read -ra VERSION_PARTS <<< "$current_version"
          VERSION_PARTS[2]=$((VERSION_PARTS[2] + 1))
          new_version="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}"
          
          mvn versions:set -DnewVersion=$new_version
          mvn versions:commit

      - name: Commit and push version change
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add pom.xml
          git commit -m "Bump version to $new_version"
          git push

  build:
    runs-on: ubuntu-latest
    needs: versioning

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          # Use short commit SHA as tag
          SHORT_SHA=$(git rev-parse --short HEAD)
          
          # Build the image
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:$SHORT_SHA .
          
          # Push both tagged and latest images
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:$SHORT_SHA

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Docker Image
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          
          docker pull ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:$SHORT_SHA
          
          docker run ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:$SHORT_SHA 