name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java JDK 17
      - name: Set up Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Increment the version in the pom.xml
      - name: Increment Version
        run: |
          # Fetch the current version
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          
          # Increment the version (this assumes a semantic versioning format)
          IFS='.' read -ra VERSION_PARTS <<< "$current_version"
          VERSION_PARTS[2]=$((VERSION_PARTS[2] + 1))
          new_version="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}"
          
          # Set and commit the new version
          mvn versions:set -DnewVersion=$new_version
          mvn versions:commit

      # Commit and push the version change to the repository
      - name: Commit and push version change
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add pom.xml
          git commit -m "Bump version to $new_version"
          git push

  build:
    runs-on: ubuntu-latest
    needs: versioning

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub using Docker Hub credentials from GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          # Use short commit SHA as tag
          SHORT_SHA=$(git rev-parse --short HEAD)
          
          # Build the image
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:$SHORT_SHA .
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:latest .
          
          # Push both tagged and latest images
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:$SHORT_SHA
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:latest

deploy:
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Install Docker Compose V2
    - name: Install Docker Compose
      run: |
        mkdir -p ~/.docker/cli-plugins/
        curl -SL https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
        chmod +x ~/.docker/cli-plugins/docker-compose
        docker compose version

    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Deploy Docker image
    - name: Deploy Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        # Generate short SHA
        SHORT_SHA=$(git rev-parse --short HEAD)
        
        # Pull the image
        docker pull $DOCKER_USERNAME/simple-java-maven-app:$SHORT_SHA
        
        # Run docker compose
        docker compose up -d